const response = {
  tag: "#PGP20RV0P",
  name: "-ＺＥＤ-",
  townHallLevel: 16,
  townHallWeaponLevel: 1,
  expLevel: 258,
  trophies: 5822,
  bestTrophies: 6036,
  warStars: 3305,
  attackWins: 247,
  defenseWins: 0,
  builderHallLevel: 10,
  builderBaseTrophies: 4346,
  bestBuilderBaseTrophies: 5235,
  role: "member",
  warPreference: "in",
  donations: 1,
  donationsReceived: 0,
  clanCapitalContributions: 1957530,
  clan: {
    tag: "#2L2LQGVR9",
    name: "_-IDeaL TeaM-_",
    clanLevel: 5,
    badgeUrls: {
      small:
        "https://api-assets.clashofclans.com/badges/70/fgNWffiV_HKgsYVWZXnTUoEsQnvB3djdRB9em0DI-gE.png",
      large:
        "https://api-assets.clashofclans.com/badges/512/fgNWffiV_HKgsYVWZXnTUoEsQnvB3djdRB9em0DI-gE.png",
      medium:
        "https://api-assets.clashofclans.com/badges/200/fgNWffiV_HKgsYVWZXnTUoEsQnvB3djdRB9em0DI-gE.png",
    },
  },
  league: {
    id: 29000022,
    name: "Legend League",
    iconUrls: {
      small:
        "https://api-assets.clashofclans.com/leagues/72/R2zmhyqQ0_lKcDR5EyghXCxgyC9mm_mVMIjAbmGoZtw.png",
      tiny: "https://api-assets.clashofclans.com/leagues/36/R2zmhyqQ0_lKcDR5EyghXCxgyC9mm_mVMIjAbmGoZtw.png",
      medium:
        "https://api-assets.clashofclans.com/leagues/288/R2zmhyqQ0_lKcDR5EyghXCxgyC9mm_mVMIjAbmGoZtw.png",
    },
  },
  builderBaseLeague: { id: 44000031, name: "Titanium League I" },
  legendStatistics: {
    legendTrophies: 14196,
    previousSeason: { id: "2024-03", rank: 15589, trophies: 5770 },
    bestSeason: { id: "2023-10", rank: 6756, trophies: 5861 },
    bestBuilderBaseSeason: { id: "2022-11", rank: 65219, trophies: 5206 },
    currentSeason: { rank: 63, trophies: 5822 },
  },
  achievements: [
    {
      name: "Bigger Coffers",
      stars: 3,
      value: 17,
      target: 10,
      info: "Upgrade a Gold Storage to level 10",
      completionInfo: "Highest Gold Storage level: 17",
      village: "home",
    },
    {
      name: "Get those Goblins!",
      stars: 3,
      value: 268,
      target: 150,
      info: "Win 150 Stars on the Campaign Map",
      completionInfo: "Stars in Campaign Map: 268",
      village: "home",
    },
    {
      name: "Bigger & Better",
      stars: 3,
      value: 16,
      target: 8,
      info: "Upgrade Town Hall to level 8",
      completionInfo: "Current Town Hall level: 16",
      village: "home",
    },
    {
      name: "Nice and Tidy",
      stars: 3,
      value: 8366,
      target: 500,
      info: "Remove 500 obstacles (trees, rocks, bushes)",
      completionInfo: "Total obstacles removed: 8366",
      village: "home",
    },
    {
      name: "Discover New Troops",
      stars: 3,
      value: 1,
      target: 1,
      info: "Unlock Dragon in the Barracks",
      completionInfo: null,
      village: "home",
    },
    {
      name: "Gold Grab",
      stars: 3,
      value: 2000000000,
      target: 100000000,
      info: "Steal 100000000 Gold",
      completionInfo: "Total Gold looted: 2000000000",
      village: "home",
    },
    {
      name: "Elixir Escapade",
      stars: 3,
      value: 2000000000,
      target: 100000000,
      info: "Steal 100000000 elixir",
      completionInfo: "Total Elixir looted: 2000000000",
      village: "home",
    },
    {
      name: "Sweet Victory!",
      stars: 3,
      value: 6036,
      target: 1250,
      info: "Achieve a total of 1250 trophies in Multiplayer battles",
      completionInfo: "Trophy record: 6036",
      village: "home",
    },
    {
      name: "Empire Builder",
      stars: 3,
      value: 11,
      target: 4,
      info: "Upgrade Clan Castle to level 4",
      completionInfo: "Current Clan Castle level: 11",
      village: "home",
    },
    {
      name: "Wall Buster",
      stars: 3,
      value: 201929,
      target: 2000,
      info: "Destroy 2000 Walls in Multiplayer battles",
      completionInfo: "Total Walls destroyed: 201929",
      village: "home",
    },
    {
      name: "Humiliator",
      stars: 3,
      value: 10709,
      target: 2000,
      info: "Destroy 2000 Town Halls in Multiplayer battles",
      completionInfo: "Total Town Halls destroyed: 10709",
      village: "home",
    },
    {
      name: "Union Buster",
      stars: 3,
      value: 54195,
      target: 2500,
      info: "Destroy 2500 Builder's Huts in Multiplayer battles",
      completionInfo: "Total Builder's Huts destroyed: 54195",
      village: "home",
    },
    {
      name: "Conqueror",
      stars: 3,
      value: 13205,
      target: 5000,
      info: "Win 5000 Multiplayer battles",
      completionInfo: "Total multiplayer battles won: 13205",
      village: "home",
    },
    {
      name: "Unbreakable",
      stars: 2,
      value: 1422,
      target: 5000,
      info: "Successfully defend against 5000 attacks",
      completionInfo: "Total defenses won: 1422",
      village: "home",
    },
    {
      name: "Friend in Need",
      stars: 3,
      value: 612948,
      target: 25000,
      info: "Donate 25000 capacity worth of reinforcements to Clanmates",
      completionInfo: "Total capacity donated: 612948",
      village: "home",
    },
    {
      name: "Mortar Mauler",
      stars: 3,
      value: 45523,
      target: 5000,
      info: "Destroy 5000 Mortars in Multiplayer battles",
      completionInfo: "Total Mortars destroyed: 45523",
      village: "home",
    },
    {
      name: "Heroic Heist",
      stars: 3,
      value: 59939622,
      target: 1000000,
      info: "Steal 1000000 Dark Elixir",
      completionInfo: "Total Dark Elixir looted: 59939622",
      village: "home",
    },
    {
      name: "League All-Star",
      stars: 3,
      value: 22,
      target: 1,
      info: "Become a Champion!",
      completionInfo: null,
      village: "home",
    },
    {
      name: "X-Bow Exterminator",
      stars: 3,
      value: 36765,
      target: 2500,
      info: "Destroy 2500 X-Bows in Multiplayer battles",
      completionInfo: "Total X-Bows destroyed: 36765",
      village: "home",
    },
    {
      name: "Firefighter",
      stars: 3,
      value: 24164,
      target: 5000,
      info: "Destroy 5000 Inferno Towers in Multiplayer battles",
      completionInfo: "Total Inferno Towers destroyed: 24164",
      village: "home",
    },
    {
      name: "War Hero",
      stars: 3,
      value: 3305,
      target: 1000,
      info: "Score 1000 Stars for your clan in Clan War battles",
      completionInfo: "Total Stars scored for clan in Clan War battles: 3305",
      village: "home",
    },
    {
      name: "Clan War Wealth",
      stars: 3,
      value: 2000000000,
      target: 100000000,
      info: "Collect 100000000 Gold from the Clan Castle",
      completionInfo: "Total Gold collected in Clan War bonuses: 2000000000",
      village: "home",
    },
    {
      name: "Anti-Artillery",
      stars: 3,
      value: 8917,
      target: 2000,
      info: "Destroy 2000 Eagle Artilleries in Multiplayer battles",
      completionInfo: "Total Eagle Artilleries destroyed: 8917",
      village: "home",
    },
    {
      name: "Sharing is caring",
      stars: 3,
      value: 25889,
      target: 10000,
      info: "Donate 10000 Spell storage capacity worth of Spells",
      completionInfo: "Total Spell capacity donated: 25889",
      village: "home",
    },
    {
      name: "Keep Your Account Safe!",
      stars: 0,
      value: 0,
      target: 1,
      info: "Protect your Village by connecting to a social network",
      completionInfo: "Completed!",
      village: "home",
    },
    {
      name: "Master Engineering",
      stars: 3,
      value: 10,
      target: 8,
      info: "Upgrade Builder Hall to level 8",
      completionInfo: "Current Builder Hall level: 10",
      village: "builderBase",
    },
    {
      name: "Next Generation Model",
      stars: 3,
      value: 1,
      target: 1,
      info: "Unlock Power P.E.K.K.A in the Builder Barracks",
      completionInfo: null,
      village: "builderBase",
    },
    {
      name: "Un-Build It",
      stars: 3,
      value: 3133,
      target: 2000,
      info: "Destroy 2000 Builder Halls in Builder Battles",
      completionInfo: "Total Builder Halls destroyed: 3133",
      village: "builderBase",
    },
    {
      name: "Champion Builder",
      stars: 3,
      value: 5235,
      target: 3000,
      info: "Achieve a total of 3000 trophies in Builder Battles",
      completionInfo: "Builder Trophy record: 5235",
      village: "builderBase",
    },
    {
      name: "High Gear",
      stars: 3,
      value: 3,
      target: 3,
      info: "Gear Up 3 buildings using the Master Builder",
      completionInfo: "Total buildings geared up: 3",
      village: "builderBase",
    },
    {
      name: "Hidden Treasures",
      stars: 3,
      value: 1,
      target: 1,
      info: "Rebuild Battle Machine",
      completionInfo: null,
      village: "builderBase",
    },
    {
      name: "Games Champion",
      stars: 3,
      value: 284930,
      target: 100000,
      info: "Earn 100000 points in Clan Games",
      completionInfo: "Total Clan Games points: 284930",
      village: "home",
    },
    {
      name: "Dragon Slayer",
      stars: 1,
      value: 5,
      target: 1,
      info: "Slay the Giant Dragon on the Campaign Map",
      completionInfo: null,
      village: "home",
    },
    {
      name: "War League Legend",
      stars: 3,
      value: 965,
      target: 250,
      info: "Score 250 Stars for your clan in War League battles",
      completionInfo: "Total Stars scored for clan in War League battles: 965",
      village: "home",
    },
    {
      name: "Keep Your Account Safe!",
      stars: 0,
      value: 0,
      target: 1,
      info: "Connect your account to Supercell ID for safe keeping.",
      completionInfo: "Completed!",
      village: "home",
    },
    {
      name: "Well Seasoned",
      stars: 3,
      value: 198790,
      target: 50000,
      info: "Earn 50000 points in Season Challenges",
      completionInfo: "Total Season Challenges points: 198790",
      village: "home",
    },
    {
      name: "Shattered and Scattered",
      stars: 3,
      value: 12443,
      target: 4000,
      info: "Destroy 4000 Scattershots in Multiplayer battles",
      completionInfo: "Total Scattershots destroyed: 12443",
      village: "home",
    },
    {
      name: "Not So Easy This Time",
      stars: 3,
      value: 5086,
      target: 2000,
      info: "Destroy 2000 weaponized Town Halls in Multiplayer battles",
      completionInfo: "Weaponized Town Halls destroyed: 5086",
      village: "home",
    },
    {
      name: "Bust This!",
      stars: 3,
      value: 23804,
      target: 2500,
      info: "Destroy 2500 weaponized Builder's Huts in Multiplayer battles",
      completionInfo: "Total weaponized Builder's Huts destroyed: 23804",
      village: "home",
    },
    {
      name: "Superb Work",
      stars: 2,
      value: 208,
      target: 250,
      info: "Boost a Super Troop 250 times",
      completionInfo: "Total times Super Troops boosted: 208",
      village: "home",
    },
    {
      name: "Siege Sharer",
      stars: 2,
      value: 2175,
      target: 5000,
      info: "Donate 5000 Siege Machines",
      completionInfo: "Total Siege Machines donated: 2175",
      village: "home",
    },
    {
      name: "Aggressive Capitalism",
      stars: 3,
      value: 1157931,
      target: 1000000,
      info: "Loot 1000000 Capital Gold during Raid attacks",
      completionInfo: "Total Capital Gold looted: 1157931",
      village: "clanCapital",
    },
    {
      name: "Most Valuable Clanmate",
      stars: 2,
      value: 1957530,
      target: 2000000,
      info: "Contribute 2000000 Capital Gold to upgrades in the Clan Capital",
      completionInfo: "Total Capital Gold contributed: 1957530",
      village: "clanCapital",
    },
    {
      name: "Counterspell",
      stars: 3,
      value: 5093,
      target: 4000,
      info: "Destroy 4000 Spell Towers in Multiplayer Battles",
      completionInfo: "Total Spell Towers Destroyed: 5093",
      village: "home",
    },
    {
      name: "Monolith Masher",
      stars: 3,
      value: 2417,
      target: 2000,
      info: "Destroy 2000 Monoliths in Multiplayer Battles",
      completionInfo: "Total Monoliths Destroyed: 2417",
      village: "home",
    },
    {
      name: "Ungrateful Child",
      stars: 1,
      value: 1,
      target: 1,
      info: "Defeat M.O.M.M.A on the Campaign Map",
      completionInfo: null,
      village: "home",
    },
  ],
  playerHouse: { elements: [[Object], [Object], [Object], [Object]] },
  labels: [
    { id: 57000001, name: "Clan War League", iconUrls: [Object] },
    { id: 57000002, name: "Trophy Pushing", iconUrls: [Object] },
    { id: 57000004, name: "Clan Games", iconUrls: [Object] },
  ],
  troops: [
    { name: "Barbarian", level: 12, maxLevel: 12, village: "home" },
    { name: "Archer", level: 12, maxLevel: 12, village: "home" },
    { name: "Goblin", level: 9, maxLevel: 9, village: "home" },
    { name: "Giant", level: 12, maxLevel: 12, village: "home" },
    { name: "Wall Breaker", level: 12, maxLevel: 12, village: "home" },
    { name: "Balloon", level: 11, maxLevel: 11, village: "home" },
    { name: "Wizard", level: 12, maxLevel: 12, village: "home" },
    { name: "Healer", level: 9, maxLevel: 9, village: "home" },
    { name: "Dragon", level: 11, maxLevel: 11, village: "home" },
    { name: "P.E.K.K.A", level: 11, maxLevel: 11, village: "home" },
    { name: "Minion", level: 11, maxLevel: 12, village: "home" },
    { name: "Hog Rider", level: 12, maxLevel: 13, village: "home" },
    { name: "Valkyrie", level: 11, maxLevel: 11, village: "home" },
    { name: "Golem", level: 13, maxLevel: 13, village: "home" },
    { name: "Witch", level: 7, maxLevel: 7, village: "home" },
    { name: "Lava Hound", level: 6, maxLevel: 6, village: "home" },
    { name: "Bowler", level: 8, maxLevel: 8, village: "home" },
    { name: "Baby Dragon", level: 10, maxLevel: 10, village: "home" },
    { name: "Miner", level: 9, maxLevel: 10, village: "home" },
    { name: "Super Barbarian", level: 1, maxLevel: 8, village: "home" },
    { name: "Super Archer", level: 1, maxLevel: 8, village: "home" },
    {
      name: "Super Wall Breaker",
      level: 1,
      maxLevel: 8,
      superTroopIsActive: true,
      village: "home",
    },
    { name: "Super Giant", level: 1, maxLevel: 8, village: "home" },
    {
      name: "Raged Barbarian",
      level: 18,
      maxLevel: 20,
      village: "builderBase",
    },
    {
      name: "Sneaky Archer",
      level: 20,
      maxLevel: 20,
      village: "builderBase",
    },
    {
      name: "Beta Minion",
      level: 18,
      maxLevel: 20,
      village: "builderBase",
    },
    {
      name: "Boxer Giant",
      level: 18,
      maxLevel: 20,
      village: "builderBase",
    },
    { name: "Bomber", level: 20, maxLevel: 20, village: "builderBase" },
    {
      name: "Power P.E.K.K.A",
      level: 20,
      maxLevel: 20,
      village: "builderBase",
    },
    {
      name: "Cannon Cart",
      level: 18,
      maxLevel: 20,
      village: "builderBase",
    },
    {
      name: "Drop Ship",
      level: 18,
      maxLevel: 20,
      village: "builderBase",
    },
    {
      name: "Baby Dragon",
      level: 18,
      maxLevel: 20,
      village: "builderBase",
    },
    {
      name: "Night Witch",
      level: 18,
      maxLevel: 20,
      village: "builderBase",
    },
    { name: "Wall Wrecker", level: 5, maxLevel: 5, village: "home" },
    { name: "Battle Blimp", level: 4, maxLevel: 4, village: "home" },
    { name: "Yeti", level: 5, maxLevel: 6, village: "home" },
    {
      name: "Sneaky Goblin",
      level: 1,
      maxLevel: 5,
      superTroopIsActive: true,
      village: "home",
    },
    { name: "Super Miner", level: 1, maxLevel: 10, village: "home" },
    { name: "Rocket Balloon", level: 1, maxLevel: 7, village: "home" },
    { name: "Ice Golem", level: 8, maxLevel: 8, village: "home" },
    { name: "Electro Dragon", level: 7, maxLevel: 7, village: "home" },
    { name: "Stone Slammer", level: 5, maxLevel: 5, village: "home" },
    { name: "Inferno Dragon", level: 1, maxLevel: 10, village: "home" },
    { name: "Super Valkyrie", level: 1, maxLevel: 11, village: "home" },
    { name: "Dragon Rider", level: 3, maxLevel: 4, village: "home" },
    { name: "Super Witch", level: 1, maxLevel: 7, village: "home" },
    {
      name: "Hog Glider",
      level: 18,
      maxLevel: 20,
      village: "builderBase",
    },
    { name: "Siege Barracks", level: 5, maxLevel: 5, village: "home" },
    { name: "Ice Hound", level: 1, maxLevel: 6, village: "home" },
    { name: "Super Bowler", level: 1, maxLevel: 8, village: "home" },
    { name: "Super Dragon", level: 1, maxLevel: 9, village: "home" },
    { name: "Headhunter", level: 3, maxLevel: 3, village: "home" },
    { name: "Super Wizard", level: 1, maxLevel: 8, village: "home" },
    { name: "Super Minion", level: 1, maxLevel: 9, village: "home" },
    { name: "Log Launcher", level: 4, maxLevel: 5, village: "home" },
    { name: "Flame Flinger", level: 4, maxLevel: 5, village: "home" },
    { name: "Battle Drill", level: 4, maxLevel: 4, village: "home" },
    { name: "Electro Titan", level: 3, maxLevel: 4, village: "home" },
    {
      name: "Apprentice Warden",
      level: 4,
      maxLevel: 4,
      village: "home",
    },
    {
      name: "Super Hog Rider",
      level: 1,
      maxLevel: 10,
      village: "home",
    },
    {
      name: "Electrofire Wizard",
      level: 1,
      maxLevel: 20,
      village: "builderBase",
    },
    { name: "Root Rider", level: 3, maxLevel: 3, village: "home" },
    { name: "L.A.S.S.I", level: 15, maxLevel: 15, village: "home" },
    { name: "Mighty Yak", level: 15, maxLevel: 15, village: "home" },
    { name: "Electro Owl", level: 15, maxLevel: 15, village: "home" },
    { name: "Unicorn", level: 10, maxLevel: 10, village: "home" },
    { name: "Phoenix", level: 10, maxLevel: 10, village: "home" },
    { name: "Poison Lizard", level: 10, maxLevel: 10, village: "home" },
    { name: "Diggy", level: 10, maxLevel: 10, village: "home" },
    { name: "Frosty", level: 10, maxLevel: 10, village: "home" },
    { name: "Spirit Fox", level: 10, maxLevel: 10, village: "home" },
  ],
  heroes: [
    {
      name: "Barbarian King",
      level: 95,
      maxLevel: 95,
      equipment: [Array],
      village: "home",
    },
    {
      name: "Archer Queen",
      level: 95,
      maxLevel: 95,
      equipment: [Array],
      village: "home",
    },
    {
      name: "Grand Warden",
      level: 70,
      maxLevel: 70,
      equipment: [Array],
      village: "home",
    },
    {
      name: "Battle Machine",
      level: 35,
      maxLevel: 35,
      village: "builderBase",
    },
    {
      name: "Royal Champion",
      level: 45,
      maxLevel: 45,
      equipment: [Array],
      village: "home",
    },
    {
      name: "Battle Copter",
      level: 34,
      maxLevel: 35,
      village: "builderBase",
    },
  ],
  heroEquipment: [
    {
      name: "Giant Gauntlet",
      level: 23,
      maxLevel: 27,
      village: "home",
    },
    { name: "Frozen Arrow", level: 27, maxLevel: 27, village: "home" },
    { name: "Fireball", level: 11, maxLevel: 27, village: "home" },
    {
      name: "Barbarian Puppet",
      level: 17,
      maxLevel: 18,
      village: "home",
    },
    { name: "Rage Vial", level: 18, maxLevel: 18, village: "home" },
    { name: "Archer Puppet", level: 17, maxLevel: 18, village: "home" },
    {
      name: "Invisibility Vial",
      level: 18,
      maxLevel: 18,
      village: "home",
    },
    { name: "Eternal Tome", level: 18, maxLevel: 18, village: "home" },
    { name: "Life Gem", level: 18, maxLevel: 18, village: "home" },
    {
      name: "Seeking Shield",
      level: 18,
      maxLevel: 18,
      village: "home",
    },
    { name: "Royal Gem", level: 18, maxLevel: 18, village: "home" },
    {
      name: "Earthquake Boots",
      level: 5,
      maxLevel: 18,
      village: "home",
    },
    {
      name: "Hog Rider Puppet",
      level: 2,
      maxLevel: 18,
      village: "home",
    },
    { name: "Vampstache", level: 17, maxLevel: 18, village: "home" },
    { name: "Haste Vial", level: 17, maxLevel: 18, village: "home" },
    { name: "Giant Arrow", level: 8, maxLevel: 18, village: "home" },
    { name: "Healer Puppet", level: 2, maxLevel: 18, village: "home" },
    { name: "Rage Gem", level: 5, maxLevel: 18, village: "home" },
    { name: "Healing Tome", level: 2, maxLevel: 18, village: "home" },
  ],
  spells: [
    {
      name: "Lightning Spell",
      level: 11,
      maxLevel: 11,
      village: "home",
    },
    { name: "Healing Spell", level: 10, maxLevel: 10, village: "home" },
    { name: "Rage Spell", level: 6, maxLevel: 6, village: "home" },
    { name: "Jump Spell", level: 5, maxLevel: 5, village: "home" },
    { name: "Freeze Spell", level: 7, maxLevel: 7, village: "home" },
    { name: "Poison Spell", level: 10, maxLevel: 10, village: "home" },
    {
      name: "Earthquake Spell",
      level: 5,
      maxLevel: 5,
      village: "home",
    },
    { name: "Haste Spell", level: 5, maxLevel: 5, village: "home" },
    { name: "Clone Spell", level: 8, maxLevel: 8, village: "home" },
    { name: "Skeleton Spell", level: 8, maxLevel: 8, village: "home" },
    { name: "Bat Spell", level: 6, maxLevel: 6, village: "home" },
    {
      name: "Invisibility Spell",
      level: 4,
      maxLevel: 4,
      village: "home",
    },
    { name: "Recall Spell", level: 4, maxLevel: 5, village: "home" },
    {
      name: "Overgrowth Spell",
      level: 2,
      maxLevel: 4,
      village: "home",
    },
  ],
};

const sliced = Object.fromEntries(Object.entries(response).slice(0, 19));
console.log(sliced);
