const response = {
  tag: "#9YC98YPV",
  name: "Покровители АДА",
  type: "closed",
  description:
    "Коль есть красавица, вино и чанга звон,\n" +
    "И берег над ручьем ветвями осенен,\n" +
    "Не надо лучшего, пусть мир зовется адом.\n" +
    "И если есть эдем, поверь, не лучше он!",
  location: {
    id: 32000193,
    name: "Russia",
    isCountry: true,
    countryCode: "RU",
  },
  isFamilyFriendly: false,
  badgeUrls: {
    small:
      "https://api-assets.clashofclans.com/badges/70/evgm0hDktGXpmLDnXvNu5ja4Kfv1z_R0BSLRRcu8YT4.png",
    large:
      "https://api-assets.clashofclans.com/badges/512/evgm0hDktGXpmLDnXvNu5ja4Kfv1z_R0BSLRRcu8YT4.png",
    medium:
      "https://api-assets.clashofclans.com/badges/200/evgm0hDktGXpmLDnXvNu5ja4Kfv1z_R0BSLRRcu8YT4.png",
  },
  clanLevel: 33,
  clanPoints: 58412,
  clanBuilderBasePoints: 47946,
  clanCapitalPoints: 5164,
  capitalLeague: { id: 85000022, name: "Legend League" },
  requiredTrophies: 5000,
  warFrequency: "always",
  warWinStreak: 1,
  warWins: 843,
  isWarLogPublic: false,
  warLeague: { id: 48000018, name: "Champion League I" },
  members: 49,
  memberList: [
    {
      tag: "#20UY2CUJG",
      name: "⭐️MAVERICK⭐️",
      role: "coLeader",
      townHallLevel: 16,
      expLevel: 247,
      league: [Object],
      trophies: 5980,
      builderBaseTrophies: 3011,
      clanRank: 1,
      previousClanRank: 3,
      donations: 53,
      donationsReceived: 1602,
      playerHouse: [Object],
      builderBaseLeague: [Object],
    },
    {
      tag: "#LJ8LR2Y8",
      name: "Loreley",
      role: "coLeader",
      townHallLevel: 16,
      expLevel: 287,
      league: [Object],
      trophies: 5964,
      builderBaseTrophies: 3605,
      clanRank: 2,
      previousClanRank: 7,
      donations: 1199,
      donationsReceived: 949,
      playerHouse: [Object],
      builderBaseLeague: [Object],
    },
    {
      tag: "#2V2L2QR28",
      name: "Parviz",
      role: "coLeader",
      townHallLevel: 16,
      expLevel: 273,
      league: [Object],
      trophies: 5962,
      builderBaseTrophies: 4644,
      clanRank: 3,
      previousClanRank: 8,
      donations: 1906,
      donationsReceived: 976,
      playerHouse: [Object],
      builderBaseLeague: [Object],
    },
    {
      tag: "#9UGU2YR0",
      name: "Кукешка",
      role: "coLeader",
      townHallLevel: 16,
      expLevel: 268,
      league: [Object],
      trophies: 5951,
      builderBaseTrophies: 4031,
      clanRank: 4,
      previousClanRank: 14,
      donations: 4419,
      donationsReceived: 8465,
      playerHouse: [Object],
      builderBaseLeague: [Object],
    },
    {
      tag: "#89CYGP8UG",
      name: "Артем777",
      role: "coLeader",
      townHallLevel: 16,
      expLevel: 297,
      league: [Object],
      trophies: 5939,
      builderBaseTrophies: 5119,
      clanRank: 5,
      previousClanRank: 2,
      donations: 5108,
      donationsReceived: 4832,
      playerHouse: [Object],
      builderBaseLeague: [Object],
    },
    {
      tag: "#2UGCP8UUU",
      name: "U°F t¡TTuru",
      role: "coLeader",
      townHallLevel: 16,
      expLevel: 247,
      league: [Object],
      trophies: 5925,
      builderBaseTrophies: 4029,
      clanRank: 6,
      previousClanRank: 0,
      donations: 1798,
      donationsReceived: 261,
      playerHouse: [Object],
      builderBaseLeague: [Object],
    },
    {
      tag: "#2GU0UPQ2J",
      name: "gik58",
      role: "coLeader",
      townHallLevel: 16,
      expLevel: 256,
      league: [Object],
      trophies: 5923,
      builderBaseTrophies: 3501,
      clanRank: 7,
      previousClanRank: 1,
      donations: 16,
      donationsReceived: 1134,
      playerHouse: [Object],
      builderBaseLeague: [Object],
    },
    {
      tag: "#82LJCRYCP",
      name: "ķåƤåȶ̃£λь",
      role: "coLeader",
      townHallLevel: 16,
      expLevel: 245,
      league: [Object],
      trophies: 5922,
      builderBaseTrophies: 4685,
      clanRank: 8,
      previousClanRank: 12,
      donations: 0,
      donationsReceived: 454,
      playerHouse: [Object],
      builderBaseLeague: [Object],
    },
    {
      tag: "#LUYC00PC",
      name: "John Wick",
      role: "coLeader",
      townHallLevel: 16,
      expLevel: 250,
      league: [Object],
      trophies: 5913,
      builderBaseTrophies: 3468,
      clanRank: 9,
      previousClanRank: 11,
      donations: 7584,
      donationsReceived: 2576,
      playerHouse: [Object],
      builderBaseLeague: [Object],
    },
    {
      tag: "#20828QQ89",
      name: "СашаБесподобный",
      role: "coLeader",
      townHallLevel: 16,
      expLevel: 270,
      league: [Object],
      trophies: 5882,
      builderBaseTrophies: 4235,
      clanRank: 10,
      previousClanRank: 25,
      donations: 3422,
      donationsReceived: 2187,
      playerHouse: [Object],
      builderBaseLeague: [Object],
    },
    {
      tag: "#RV9U0R02",
      name: "ArcTar",
      role: "coLeader",
      townHallLevel: 16,
      expLevel: 253,
      league: [Object],
      trophies: 5881,
      builderBaseTrophies: 4077,
      clanRank: 11,
      previousClanRank: 23,
      donations: 378,
      donationsReceived: 1163,
      playerHouse: [Object],
      builderBaseLeague: [Object],
    },
    {
      tag: "#2GYG9GR9C",
      name: "QODIROV PARVIZ",
      role: "coLeader",
      townHallLevel: 16,
      expLevel: 258,
      league: [Object],
      trophies: 5863,
      builderBaseTrophies: 4575,
      clanRank: 12,
      previousClanRank: 4,
      donations: 7106,
      donationsReceived: 2831,
      playerHouse: [Object],
      builderBaseLeague: [Object],
    },
    {
      tag: "#8P0UCGJY",
      name: "Makeshka",
      role: "coLeader",
      townHallLevel: 16,
      expLevel: 258,
      league: [Object],
      trophies: 5846,
      builderBaseTrophies: 3792,
      clanRank: 13,
      previousClanRank: 5,
      donations: 3998,
      donationsReceived: 8316,
      playerHouse: [Object],
      builderBaseLeague: [Object],
    },
    {
      tag: "#YYL0UYGU0",
      name: "Andrei",
      role: "coLeader",
      townHallLevel: 16,
      expLevel: 255,
      league: [Object],
      trophies: 5840,
      builderBaseTrophies: 5042,
      clanRank: 14,
      previousClanRank: 6,
      donations: 594,
      donationsReceived: 636,
      playerHouse: [Object],
      builderBaseLeague: [Object],
    },
    {
      tag: "#L0QP8CLGG",
      name: "Metta",
      role: "coLeader",
      townHallLevel: 16,
      expLevel: 277,
      league: [Object],
      trophies: 5840,
      builderBaseTrophies: 5036,
      clanRank: 15,
      previousClanRank: 17,
      donations: 3714,
      donationsReceived: 4798,
      playerHouse: [Object],
      builderBaseLeague: [Object],
    },
    {
      tag: "#2PQJRR0JU",
      name: "ПуЗаТыЙ_кРоТ",
      role: "coLeader",
      townHallLevel: 16,
      expLevel: 263,
      league: [Object],
      trophies: 5839,
      builderBaseTrophies: 4887,
      clanRank: 16,
      previousClanRank: 0,
      donations: 454,
      donationsReceived: 210,
      playerHouse: [Object],
      builderBaseLeague: [Object],
    },
    {
      tag: "#990RRURU",
      name: "Fantasy",
      role: "coLeader",
      townHallLevel: 16,
      expLevel: 274,
      league: [Object],
      trophies: 5831,
      builderBaseTrophies: 3518,
      clanRank: 17,
      previousClanRank: 13,
      donations: 2561,
      donationsReceived: 2821,
      playerHouse: [Object],
      builderBaseLeague: [Object],
    },
    {
      tag: "#82G29PJ0U",
      name: "BlackFire",
      role: "coLeader",
      townHallLevel: 16,
      expLevel: 260,
      league: [Object],
      trophies: 5830,
      builderBaseTrophies: 3432,
      clanRank: 18,
      previousClanRank: 26,
      donations: 233,
      donationsReceived: 745,
      playerHouse: [Object],
      builderBaseLeague: [Object],
    },
    {
      tag: "#220LQUG8C",
      name: "pas",
      role: "coLeader",
      townHallLevel: 16,
      expLevel: 258,
      league: [Object],
      trophies: 5825,
      builderBaseTrophies: 5413,
      clanRank: 19,
      previousClanRank: 19,
      donations: 2446,
      donationsReceived: 2012,
      playerHouse: [Object],
      builderBaseLeague: [Object],
    },
    {
      tag: "#88GUPVG2V",
      name: "Эдгар",
      role: "coLeader",
      townHallLevel: 16,
      expLevel: 257,
      league: [Object],
      trophies: 5819,
      builderBaseTrophies: 5196,
      clanRank: 20,
      previousClanRank: 27,
      donations: 34,
      donationsReceived: 1726,
      playerHouse: [Object],
      builderBaseLeague: [Object],
    },
    {
      tag: "#GJJ0CLG",
      name: "DonPadlik",
      role: "coLeader",
      townHallLevel: 16,
      expLevel: 253,
      league: [Object],
      trophies: 5810,
      builderBaseTrophies: 3246,
      clanRank: 21,
      previousClanRank: 9,
      donations: 27750,
      donationsReceived: 10809,
      playerHouse: [Object],
      builderBaseLeague: [Object],
    },
    {
      tag: "#P2QQRCYRQ",
      name: "BORODA",
      role: "coLeader",
      townHallLevel: 16,
      expLevel: 276,
      league: [Object],
      trophies: 5809,
      builderBaseTrophies: 3734,
      clanRank: 22,
      previousClanRank: 40,
      donations: 2656,
      donationsReceived: 3260,
      playerHouse: [Object],
      builderBaseLeague: [Object],
    },
    {
      tag: "#PRGPCLJQ9",
      name: "Vortex",
      role: "coLeader",
      townHallLevel: 16,
      expLevel: 239,
      league: [Object],
      trophies: 5805,
      builderBaseTrophies: 3820,
      clanRank: 23,
      previousClanRank: 21,
      donations: 2081,
      donationsReceived: 2859,
      playerHouse: [Object],
      builderBaseLeague: [Object],
    },
    {
      tag: "#8JJV8UGQ",
      name: "Deadsh0T",
      role: "coLeader",
      townHallLevel: 16,
      expLevel: 270,
      league: [Object],
      trophies: 5803,
      builderBaseTrophies: 5458,
      clanRank: 24,
      previousClanRank: 22,
      donations: 3155,
      donationsReceived: 3826,
      playerHouse: [Object],
      builderBaseLeague: [Object],
    },
    {
      tag: "#22YG809U",
      name: "Exquisite",
      role: "leader",
      townHallLevel: 16,
      expLevel: 278,
      league: [Object],
      trophies: 5794,
      builderBaseTrophies: 4314,
      clanRank: 25,
      previousClanRank: 29,
      donations: 619,
      donationsReceived: 1846,
      playerHouse: [Object],
      builderBaseLeague: [Object],
    },
    {
      tag: "#2YPVJ28QG",
      name: "FC BARCELONA",
      role: "coLeader",
      townHallLevel: 16,
      expLevel: 245,
      league: [Object],
      trophies: 5790,
      builderBaseTrophies: 4502,
      clanRank: 26,
      previousClanRank: 30,
      donations: 120,
      donationsReceived: 1696,
      playerHouse: [Object],
      builderBaseLeague: [Object],
    },
    {
      tag: "#LURVQ2J9",
      name: "AERTON",
      role: "coLeader",
      townHallLevel: 16,
      expLevel: 278,
      league: [Object],
      trophies: 5786,
      builderBaseTrophies: 4853,
      clanRank: 27,
      previousClanRank: 33,
      donations: 503,
      donationsReceived: 3482,
      builderBaseLeague: [Object],
    },
    {
      tag: "#YCGGPVV9J",
      name: "⭐FLAME⭐",
      role: "coLeader",
      townHallLevel: 16,
      expLevel: 271,
      league: [Object],
      trophies: 5783,
      builderBaseTrophies: 4483,
      clanRank: 28,
      previousClanRank: 28,
      donations: 3352,
      donationsReceived: 3066,
      playerHouse: [Object],
      builderBaseLeague: [Object],
    },
    {
      tag: "#92UJ9Y08P",
      name: "игорь",
      role: "coLeader",
      townHallLevel: 16,
      expLevel: 280,
      league: [Object],
      trophies: 5778,
      builderBaseTrophies: 4900,
      clanRank: 29,
      previousClanRank: 18,
      donations: 3201,
      donationsReceived: 3444,
      playerHouse: [Object],
      builderBaseLeague: [Object],
    },
    {
      tag: "#29C0U98GJ",
      name: "В≋и≋т≋а≋л≋и≋к≋",
      role: "coLeader",
      townHallLevel: 16,
      expLevel: 253,
      league: [Object],
      trophies: 5770,
      builderBaseTrophies: 3850,
      clanRank: 30,
      previousClanRank: 10,
      donations: 2187,
      donationsReceived: 4199,
      playerHouse: [Object],
      builderBaseLeague: [Object],
    },
    {
      tag: "#9Q9GJ8R08",
      name: "Андрей",
      role: "coLeader",
      townHallLevel: 16,
      expLevel: 305,
      league: [Object],
      trophies: 5770,
      builderBaseTrophies: 5288,
      clanRank: 31,
      previousClanRank: 35,
      donations: 7014,
      donationsReceived: 4384,
      playerHouse: [Object],
      builderBaseLeague: [Object],
    },
    {
      tag: "#9YQ90LQL",
      name: "Bazhon",
      role: "coLeader",
      townHallLevel: 16,
      expLevel: 296,
      league: [Object],
      trophies: 5760,
      builderBaseTrophies: 1571,
      clanRank: 32,
      previousClanRank: 0,
      donations: 21,
      donationsReceived: 53,
      playerHouse: [Object],
      builderBaseLeague: [Object],
    },
    {
      tag: "#8RCV2RLGP",
      name: "pmartin",
      role: "coLeader",
      townHallLevel: 16,
      expLevel: 269,
      league: [Object],
      trophies: 5746,
      builderBaseTrophies: 4985,
      clanRank: 33,
      previousClanRank: 0,
      donations: 139,
      donationsReceived: 0,
      playerHouse: [Object],
      builderBaseLeague: [Object],
    },
    {
      tag: "#9RLGYVQ00",
      name: "СЕРДЦЕ ЛЬВА",
      role: "coLeader",
      townHallLevel: 16,
      expLevel: 281,
      league: [Object],
      trophies: 5732,
      builderBaseTrophies: 3684,
      clanRank: 34,
      previousClanRank: 36,
      donations: 2396,
      donationsReceived: 3347,
      playerHouse: [Object],
      builderBaseLeague: [Object],
    },
    {
      tag: "#2RYP29GR2",
      name: "Леонид",
      role: "coLeader",
      townHallLevel: 16,
      expLevel: 250,
      league: [Object],
      trophies: 5707,
      builderBaseTrophies: 4643,
      clanRank: 35,
      previousClanRank: 32,
      donations: 390,
      donationsReceived: 8185,
      playerHouse: [Object],
      builderBaseLeague: [Object],
    },
    {
      tag: "#292RU8PY0",
      name: "PLINTO",
      role: "coLeader",
      townHallLevel: 16,
      expLevel: 265,
      league: [Object],
      trophies: 5683,
      builderBaseTrophies: 3906,
      clanRank: 36,
      previousClanRank: 0,
      donations: 30,
      donationsReceived: 0,
      playerHouse: [Object],
      builderBaseLeague: [Object],
    },
    {
      tag: "#2PVLCVGLJ",
      name: "¡sl°MBeK",
      role: "coLeader",
      townHallLevel: 16,
      expLevel: 324,
      league: [Object],
      trophies: 5678,
      builderBaseTrophies: 3823,
      clanRank: 37,
      previousClanRank: 42,
      donations: 1840,
      donationsReceived: 3923,
      playerHouse: [Object],
      builderBaseLeague: [Object],
    },
    {
      tag: "#YCRRPC920",
      name: ".:ТаТьянка:.",
      role: "coLeader",
      townHallLevel: 16,
      expLevel: 233,
      league: [Object],
      trophies: 5677,
      builderBaseTrophies: 2719,
      clanRank: 38,
      previousClanRank: 43,
      donations: 135,
      donationsReceived: 561,
      playerHouse: [Object],
      builderBaseLeague: [Object],
    },
    {
      tag: "#29UL9J9C2",
      name: "✨ＡＮＤＲＥＹ✨",
      role: "coLeader",
      townHallLevel: 16,
      expLevel: 328,
      league: [Object],
      trophies: 5657,
      builderBaseTrophies: 5133,
      clanRank: 39,
      previousClanRank: 41,
      donations: 6250,
      donationsReceived: 2803,
      playerHouse: [Object],
      builderBaseLeague: [Object],
    },
    {
      tag: "#8YL80U9GL",
      name: "Олло",
      role: "coLeader",
      townHallLevel: 16,
      expLevel: 252,
      league: [Object],
      trophies: 5655,
      builderBaseTrophies: 4336,
      clanRank: 40,
      previousClanRank: 15,
      donations: 4528,
      donationsReceived: 2355,
      playerHouse: [Object],
      builderBaseLeague: [Object],
    },
    {
      tag: "#PCLGC98CG",
      name: "Wovchik",
      role: "coLeader",
      townHallLevel: 16,
      expLevel: 293,
      league: [Object],
      trophies: 5646,
      builderBaseTrophies: 4880,
      clanRank: 41,
      previousClanRank: 20,
      donations: 4772,
      donationsReceived: 11257,
      playerHouse: [Object],
      builderBaseLeague: [Object],
    },
    {
      tag: "#2PGQ8C9JU",
      name: "V1LKA",
      role: "coLeader",
      townHallLevel: 16,
      expLevel: 240,
      league: [Object],
      trophies: 5633,
      builderBaseTrophies: 2967,
      clanRank: 42,
      previousClanRank: 31,
      donations: 1964,
      donationsReceived: 3767,
      builderBaseLeague: [Object],
    },
    {
      tag: "#YPPRV9YQY",
      name: "Mr. Shaizen",
      role: "coLeader",
      townHallLevel: 16,
      expLevel: 259,
      league: [Object],
      trophies: 5598,
      builderBaseTrophies: 4114,
      clanRank: 43,
      previousClanRank: 39,
      donations: 225,
      donationsReceived: 1557,
      playerHouse: [Object],
      builderBaseLeague: [Object],
    },
    {
      tag: "#2Q8PGGVCU",
      name: "kloun",
      role: "coLeader",
      townHallLevel: 16,
      expLevel: 317,
      league: [Object],
      trophies: 5593,
      builderBaseTrophies: 4424,
      clanRank: 44,
      previousClanRank: 46,
      donations: 4229,
      donationsReceived: 4462,
      playerHouse: [Object],
      builderBaseLeague: [Object],
    },
    {
      tag: "#Y9JR0YVJ",
      name: "Alex",
      role: "coLeader",
      townHallLevel: 16,
      expLevel: 255,
      league: [Object],
      trophies: 5584,
      builderBaseTrophies: 4190,
      clanRank: 45,
      previousClanRank: 34,
      donations: 1510,
      donationsReceived: 7629,
      playerHouse: [Object],
      builderBaseLeague: [Object],
    },
    {
      tag: "#Y0QULRCVU",
      name: "BurNing",
      role: "coLeader",
      townHallLevel: 16,
      expLevel: 249,
      league: [Object],
      trophies: 5462,
      builderBaseTrophies: 5019,
      clanRank: 46,
      previousClanRank: 48,
      donations: 153,
      donationsReceived: 1774,
      playerHouse: [Object],
      builderBaseLeague: [Object],
    },
    {
      tag: "#92R8Q2U9",
      name: "Hanka38rusDima",
      role: "coLeader",
      townHallLevel: 16,
      expLevel: 263,
      league: [Object],
      trophies: 5450,
      builderBaseTrophies: 5164,
      clanRank: 47,
      previousClanRank: 49,
      donations: 3722,
      donationsReceived: 3528,
      playerHouse: [Object],
      builderBaseLeague: [Object],
    },
    {
      tag: "#L0JQ9JCUY",
      name: "chi chi",
      role: "coLeader",
      townHallLevel: 16,
      expLevel: 248,
      league: [Object],
      trophies: 5386,
      builderBaseTrophies: 5377,
      clanRank: 48,
      previousClanRank: 44,
      donations: 3008,
      donationsReceived: 590,
      playerHouse: [Object],
      builderBaseLeague: [Object],
    },
    {
      tag: "#2J2RRQ98V",
      name: "Royal",
      role: "coLeader",
      townHallLevel: 16,
      expLevel: 245,
      league: [Object],
      trophies: 5379,
      builderBaseTrophies: 4514,
      clanRank: 49,
      previousClanRank: 47,
      donations: 0,
      donationsReceived: 401,
      playerHouse: [Object],
      builderBaseLeague: [Object],
    },
  ],
  labels: [
    { id: 56000000, name: "Clan Wars", iconUrls: [Object] },
    { id: 56000001, name: "Clan War League", iconUrls: [Object] },
    { id: 56000002, name: "Trophy Pushing", iconUrls: [Object] },
  ],
  requiredBuilderBaseTrophies: 0,
  requiredTownhallLevel: 16,
  clanCapital: {
    capitalHallLevel: 10,
    districts: [
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
    ],
  },
  chatLanguage: { id: 75000012, name: "Pусский", languageCode: "RU" },
};
